GET localhost:7070/api/hotel

###
GET localhost:7070/api/hotel/2

###
POST http://localhost:7070/api/hotel
Content-Type: application/json

{

  "name": "Hotel California",
  "address": "1234 California St",
  "rooms": [
    {

      "roomNumber": "601",
      "price": 100.00
    },
    {

      "roomNumber": "602",
      "price": 200
    }
  ]
}

###
PUT http://localhost:7070/api/hotel/6
Content-Type: : application/json

{

  "name": "Hotel California",
  "address": "1234 California St",
  "rooms": [
    {
      "id": 51,
      "hotelId": 6,
      "roomNumber": "601",
      "price": 150.00
    },
    {
      "id": 52,
      "hotelId": 6,
      "roomNumber": "602",
      "price": 500.00
    }
  ]
}

###
DELETE http://localhost:7070/api/hotel/5

###
GET http://localhost:7070/api/hotel/1/rooms

###
POST http://localhost:7070/api/hotel/1/room
Content-Type: application/json

{
  "roomNumber": "111",
  "price": 200.00,
  "hotelId": 1
}




###
POST http://localhost:7070/api/auth/register
Content-Type: application/json

{
  "username": "FranckDux",
  "password": "Hej123"
}

###
POST http://localhost:7070/api/auth/login
Content-Type: application/json

{
  "username": "user2",
  "password": "Hej123"
}

###
GET http://localhost:7070/api/secured/demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIkZyZWRlcmlrIEZyYW5ja1wiIiwic3ViIjoidXNlcjIiLCJleHAiOjE3NDE5NDc3NjAsInJvbGVzIjoidXNlciIsInVzZXJuYW1lIjoidXNlcjIifQ.iRBorduS5IYZNZ-W-vNdrw_aaAE7FmqY1omesK9CHOE

