GET localhost:7070/api/hotel

###
GET localhost:7070/api/hotel/2

###
POST http://localhost:7070/api/hotel
Content-Type: application/json

{

  "name": "Hotel California",
  "address": "1234 California St",
  "rooms": [
    {

      "roomNumber": "601",
      "price": 100.00
    },
    {

      "roomNumber": "602",
      "price": 200
    }
  ]
}

